### ISSUE TITLE
Auth Service

### ISSUE THREAD

**Issue by vinicius73** [artesaos/forum#1]
- [x] Create Account #7 
- [x] Login (e-mail and username) #6 
- [x] Social Login #14 
  - [x] Github
  - [x] Facebook
  - [x] Twitter
  - [x] Google +

**Comment by mandado** [comment]
@vinicius73  aqui vai usar socialite ?

**Comment by vinicius73** [comment]
Provavelmente sim @mandado

**Comment by mandado** [comment]
então é que queria tentar fazer hehehe. por isso to perguntando, já tem ideia de como vai ficar esquematizado ?

**Comment by vinicius73** [comment]
Não.
Fica a vontade para bolar uma maneira legal @mandado

**Comment by vinicius73** [comment]
Concluido #14 @lucas-macedo 
Faltam testes.
